version: "3"
services:
  web:
    container_name: mysql_operations
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/mysql_operations
    env_file:
      - ./certificate/mysql_operations.env
    ports:
      - "3000:3000"